### ISSUE TITLE
Is there a conversion code that can merge LLM with its LoRA weights using TAIA method?

### ISSUE THREAD

**Issue by ktgiahieu** [pixas/TAIA_LLM#1]
Thank you for the nice paper and findings!
If I understand correctly, TAIA can be used for any LoRA-finetuned adapter weight, but with a different way to merge parameters (i.e. only retain attention updates). Please correct me if I'm wrong.

May I ask if there is a conversion code that can merge:
   a frozen LLM (i.e. Llama) 
+ its LoRA weights (adapter_model.bin) 
-> merged final weights using TAIA?

Thank you very much for sharing!

**Comment by pixas** [comment]
Hello, In TAIA, you can merge weights as:
```python
model = AutoModelForCausalLM.from_pretrained(pretrained_path, low_cpu_mem_usage=True, trust_remote_code=True, **kwargs)
lora_save_path = "" # your lora save path
from peft import PeftModel, LoraConfig
config = LoraConfig.from_pretrained(lora_save_path)
config.target_modules = ["q_proj", "k_proj", "v_proj", "o_proj"]  # these four keywords follow the architecture of Llama and Qwen, for other pretrained LLM, please lookup the corresponding parameter names
model = PeftModel.from_pretrained(model, lora_save_path, config=config)
model = model.merge_and_unload()
```
We conduct experiments on `transformers==4.38.1`, so if you meet unexpected behaviors (such as still loading all parameters), please use `pip install transformers==4.38.1` to align with our settings.

**Comment by ktgiahieu** [comment]
Thank you for your prompt reply!
I am sorry if I miss it, but what should I set as `target_modules` in my LoraConfig during **training**?

**Comment by pixas** [comment]
TAIA follows the vanilla LoRA tuning technique to put all linear layers to the `target_modules`. To reproduce our results, you can just use:
```python
lora_config = LoraConfig(
                r=training_args.lora_r,
                lora_alpha=training_args.lora_alpha,
                target_modules=find_all_linear_names(model, False, whether_wrap_ffn=training_args.wrap_ffn if model_args.num_experts <= 1 else False, whether_wrap_attn=training_args.wrap_attn, layer_cls=decoder_layer_cls),
                lora_dropout=training_args.lora_dropout,
                bias=training_args.lora_bias,
                task_type="CAUSAL_LM",
                use_rslora=training_args.lora_use_rs
            )
```
which is also illustrated in L623 of `taia/train/train.py`.
For LoRA, just make `training_args.wrap_ffn` and `training_args.wrap_attn` to both True.

**Comment by ktgiahieu** [comment]
Thank you very much. This is very helpful for me! Hope your paper get accepted soon!
